version: "3"
services:
  drupal:
    image: bitnami/drupal:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_HOST=db
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_USER=your_username
      - MARIADB_PASSWORD=your_password
      - MARIADB_DATABASE=drupal_database
    depends_on:
      - db
    ports:
      - 80:80
    volumes:
      - drupal_data:/bitnami/drupal

  db:
    image: bitnami/mariadb:latest
    environment:
      - MYSQL_USER=fatihaykac
      - MYSQL_PASSWORD=fatih
      - MYSQL_DATABASE=drupal_database
    volumes:
      - db_data:/bitnami/mariadb

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  certbot:
    image: certbot
    volumes:
      - certbot_data:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/html --email aykac.fatih@std.izu.edu.tr -d fatihaykac.me

volumes:
  drupal_data:
  db_data:
  certbot_data: